name: IHLT3.7
channels:
  - defaults
dependencies:
  - pip=20.2.2=py37_0
  - python=3.7.9
  - pip:
    - jupyter==1.0.0
    - matplotlib==3.3.2
    - nltk==3.5
    - numpy==1.19.2
    - pandas==1.1.2
    - scipy==1.5.2
